<?php
/**
 * Template
 *
 * PHP version 5
 *
 * @category Class
 * @package  Squiggle
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Squiggle\Model;

use \ArrayAccess;
/**
 * Template Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Squiggle
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Template implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'id' => 'int',
        'name' => 'string',
        'description' => 'string',
        'thumbnail' => 'string',
        'content_html' => 'string',
        'content_plaintext' => 'string',
        'content_richtext' => 'string',
        'settings' => 'string',
        'user' => 'int',
        'template' => 'int'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'id' => 'id',
        'name' => 'name',
        'description' => 'description',
        'thumbnail' => 'thumbnail',
        'content_html' => 'content_html',
        'content_plaintext' => 'content_plaintext',
        'content_richtext' => 'content_richtext',
        'settings' => 'settings',
        'user' => 'user',
        'template' => 'template'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'id' => 'setId',
        'name' => 'setName',
        'description' => 'setDescription',
        'thumbnail' => 'setThumbnail',
        'content_html' => 'setContentHtml',
        'content_plaintext' => 'setContentPlaintext',
        'content_richtext' => 'setContentRichtext',
        'settings' => 'setSettings',
        'user' => 'setUser',
        'template' => 'setTemplate'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'id' => 'getId',
        'name' => 'getName',
        'description' => 'getDescription',
        'thumbnail' => 'getThumbnail',
        'content_html' => 'getContentHtml',
        'content_plaintext' => 'getContentPlaintext',
        'content_richtext' => 'getContentRichtext',
        'settings' => 'getSettings',
        'user' => 'getUser',
        'template' => 'getTemplate'
    );
  
    
    /**
      * $id 
      * @var int
      */
    protected $id;
    
    /**
      * $name 
      * @var string
      */
    protected $name;
    
    /**
      * $description 
      * @var string
      */
    protected $description;
    
    /**
      * $thumbnail 
      * @var string
      */
    protected $thumbnail;
    
    /**
      * $content_html 
      * @var string
      */
    protected $content_html;
    
    /**
      * $content_plaintext 
      * @var string
      */
    protected $content_plaintext;
    
    /**
      * $content_richtext 
      * @var string
      */
    protected $content_richtext;
    
    /**
      * $settings 
      * @var string
      */
    protected $settings;
    
    /**
      * $user 
      * @var int
      */
    protected $user;
    
    /**
      * $template 
      * @var int
      */
    protected $template;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            foreach ($data as $key => $value) {
                if (property_exists($this, $key)) {
                    $this->$key = $value;
                }
            }
        }
    }
    
    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
  
    /**
     * Sets id
     * @param int $id 
     * @return $this
     */
    public function setId($id)
    {
        
        $this->id = $id;
        return $this;
    }
    
    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
  
    /**
     * Sets name
     * @param string $name 
     * @return $this
     */
    public function setName($name)
    {
        
        $this->name = $name;
        return $this;
    }
    
    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }
  
    /**
     * Sets description
     * @param string $description 
     * @return $this
     */
    public function setDescription($description)
    {
        
        $this->description = $description;
        return $this;
    }
    
    /**
     * Gets thumbnail
     * @return string
     */
    public function getThumbnail()
    {
        return $this->thumbnail;
    }
  
    /**
     * Sets thumbnail
     * @param string $thumbnail 
     * @return $this
     */
    public function setThumbnail($thumbnail)
    {
        
        $this->thumbnail = $thumbnail;
        return $this;
    }
    
    /**
     * Gets content_html
     * @return string
     */
    public function getContentHtml()
    {
        return $this->content_html;
    }
  
    /**
     * Sets content_html
     * @param string $content_html 
     * @return $this
     */
    public function setContentHtml($content_html)
    {
        
        $this->content_html = $content_html;
        return $this;
    }
    
    /**
     * Gets content_plaintext
     * @return string
     */
    public function getContentPlaintext()
    {
        return $this->content_plaintext;
    }
  
    /**
     * Sets content_plaintext
     * @param string $content_plaintext 
     * @return $this
     */
    public function setContentPlaintext($content_plaintext)
    {
        
        $this->content_plaintext = $content_plaintext;
        return $this;
    }
    
    /**
     * Gets content_richtext
     * @return string
     */
    public function getContentRichtext()
    {
        return $this->content_richtext;
    }
  
    /**
     * Sets content_richtext
     * @param string $content_richtext 
     * @return $this
     */
    public function setContentRichtext($content_richtext)
    {
        
        $this->content_richtext = $content_richtext;
        return $this;
    }
    
    /**
     * Gets settings
     * @return string
     */
    public function getSettings()
    {
        return $this->settings;
    }
  
    /**
     * Sets settings
     * @param string $settings 
     * @return $this
     */
    public function setSettings($settings)
    {
        
        $this->settings = $settings;
        return $this;
    }
    
    /**
     * Gets user
     * @return int
     */
    public function getUser()
    {
        return $this->user;
    }
  
    /**
     * Sets user
     * @param int $user 
     * @return $this
     */
    public function setUser($user)
    {
        
        $this->user = $user;
        return $this;
    }
    
    /**
     * Gets template
     * @return int
     */
    public function getTemplate()
    {
        return $this->template;
    }
  
    /**
     * Sets template
     * @param int $template 
     * @return $this
     */
    public function setTemplate($template)
    {
        
        $this->template = $template;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Squiggle\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Squiggle\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
