<?php
/**
 * SquiggleApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Squiggle
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Squiggle;

use \Squiggle\Configuration;
use \Squiggle\ApiClient;
use \Squiggle\ApiException;
use \Squiggle\ObjectSerializer;

/**
 * SquiggleApiTest Class Doc Comment
 *
 * @category Class
 * @package  Squiggle
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SquiggleApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for findAddresses
     *
     * 
     *
     */
    public function test_findAddresses() {

    }
    
    /**
     * Test case for addAddress
     *
     * 
     *
     */
    public function test_addAddress() {

    }
    
    /**
     * Test case for getAddress
     *
     * 
     *
     */
    public function test_getAddress() {

    }
    
    /**
     * Test case for deleteAddress
     *
     * 
     *
     */
    public function test_deleteAddress() {

    }
    
    /**
     * Test case for editAddress
     *
     * 
     *
     */
    public function test_editAddress() {

    }
    
    /**
     * Test case for findFiles
     *
     * 
     *
     */
    public function test_findFiles() {

    }
    
    /**
     * Test case for addFile
     *
     * 
     *
     */
    public function test_addFile() {

    }
    
    /**
     * Test case for getFile
     *
     * 
     *
     */
    public function test_getFile() {

    }
    
    /**
     * Test case for deleteFile
     *
     * 
     *
     */
    public function test_deleteFile() {

    }
    
    /**
     * Test case for editFile
     *
     * 
     *
     */
    public function test_editFile() {

    }
    
    /**
     * Test case for findGlobalTemplates
     *
     * 
     *
     */
    public function test_findGlobalTemplates() {

    }
    
    /**
     * Test case for addGlobalTemplate
     *
     * 
     *
     */
    public function test_addGlobalTemplate() {

    }
    
    /**
     * Test case for getGlobalTemplate
     *
     * 
     *
     */
    public function test_getGlobalTemplate() {

    }
    
    /**
     * Test case for deleteGlobalTemplate
     *
     * 
     *
     */
    public function test_deleteGlobalTemplate() {

    }
    
    /**
     * Test case for editGlobalTemplate
     *
     * 
     *
     */
    public function test_editGlobalTemplate() {

    }
    
    /**
     * Test case for findSnippets
     *
     * 
     *
     */
    public function test_findSnippets() {

    }
    
    /**
     * Test case for addSnippet
     *
     * 
     *
     */
    public function test_addSnippet() {

    }
    
    /**
     * Test case for getSnippet
     *
     * 
     *
     */
    public function test_getSnippet() {

    }
    
    /**
     * Test case for deleteSnippet
     *
     * 
     *
     */
    public function test_deleteSnippet() {

    }
    
    /**
     * Test case for editSnippet
     *
     * 
     *
     */
    public function test_editSnippet() {

    }
    
    /**
     * Test case for findTemplates
     *
     * 
     *
     */
    public function test_findTemplates() {

    }
    
    /**
     * Test case for addTemplate
     *
     * 
     *
     */
    public function test_addTemplate() {

    }
    
    /**
     * Test case for getTemplate
     *
     * 
     *
     */
    public function test_getTemplate() {

    }
    
    /**
     * Test case for deleteTemplate
     *
     * 
     *
     */
    public function test_deleteTemplate() {

    }
    
    /**
     * Test case for editTemplate
     *
     * 
     *
     */
    public function test_editTemplate() {

    }
    
    /**
     * Test case for getAddressToken
     *
     * 
     *
     */
    public function test_getAddressToken() {

    }
    
    /**
     * Test case for getUserToken
     *
     * 
     *
     */
    public function test_getUserToken() {

    }
    
    /**
     * Test case for findUsers
     *
     * 
     *
     */
    public function test_findUsers() {

    }
    
    /**
     * Test case for addUser
     *
     * 
     *
     */
    public function test_addUser() {

    }
    
    /**
     * Test case for getUser
     *
     * 
     *
     */
    public function test_getUser() {

    }
    
    /**
     * Test case for deleteUser
     *
     * 
     *
     */
    public function test_deleteUser() {

    }
    
    /**
     * Test case for editUser
     *
     * 
     *
     */
    public function test_editUser() {

    }
    
}
