<?php
/**
 * AddressTemplateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Squiggle
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Squiggle API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Squiggle;

/**
 * AddressTemplateTest Class Doc Comment
 *
 * @category    Class */
// * @description AddressTemplate
/**
 * @package     Squiggle
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AddressTemplateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AddressTemplate"
     */
    public function testAddressTemplate()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {

    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {

    }

    /**
     * Test attribute "job_title"
     */
    public function testPropertyJobTitle()
    {

    }

    /**
     * Test attribute "tel_mobile"
     */
    public function testPropertyTelMobile()
    {

    }

    /**
     * Test attribute "tel_direct"
     */
    public function testPropertyTelDirect()
    {

    }

    /**
     * Test attribute "linkedin"
     */
    public function testPropertyLinkedin()
    {

    }

    /**
     * Test attribute "facebook"
     */
    public function testPropertyFacebook()
    {

    }

    /**
     * Test attribute "twitter"
     */
    public function testPropertyTwitter()
    {

    }

    /**
     * Test attribute "instagram"
     */
    public function testPropertyInstagram()
    {

    }

    /**
     * Test attribute "googleplus"
     */
    public function testPropertyGoogleplus()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "marketing"
     */
    public function testPropertyMarketing()
    {

    }

}
