<?php
/**
 * RenderOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Squiggle
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Squiggle API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Squiggle;

/**
 * RenderOptionsTest Class Doc Comment
 *
 * @category    Class */
// * @description RenderOptions
/**
 * @package     Squiggle
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RenderOptionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RenderOptions"
     */
    public function testRenderOptions()
    {

    }

    /**
     * Test attribute "address_id"
     */
    public function testPropertyAddressId()
    {

    }

    /**
     * Test attribute "template_id"
     */
    public function testPropertyTemplateId()
    {

    }

    /**
     * Test attribute "global_template_id"
     */
    public function testPropertyGlobalTemplateId()
    {

    }

    /**
     * Test attribute "template"
     */
    public function testPropertyTemplate()
    {

    }

    /**
     * Test attribute "context"
     */
    public function testPropertyContext()
    {

    }

}
