<?php
/**
 * ResponseLinksTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Squiggle
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Squiggle API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Squiggle;

/**
 * ResponseLinksTest Class Doc Comment
 *
 * @category    Class */
// * @description ResponseLinks
/**
 * @package     Squiggle
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseLinksTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ResponseLinks"
     */
    public function testResponseLinks()
    {

    }

    /**
     * Test attribute "self"
     */
    public function testPropertySelf()
    {

    }

    /**
     * Test attribute "related"
     */
    public function testPropertyRelated()
    {

    }

    /**
     * Test attribute "next"
     */
    public function testPropertyNext()
    {

    }

    /**
     * Test attribute "last"
     */
    public function testPropertyLast()
    {

    }

}
