<?php
/**
 * UserTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Squiggle
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Squiggle API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Squiggle;

/**
 * UserTest Class Doc Comment
 *
 * @category    Class */
// * @description User
/**
 * @package     Squiggle
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "User"
     */
    public function testUser()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {

    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {

    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {

    }

    /**
     * Test attribute "domain"
     */
    public function testPropertyDomain()
    {

    }

    /**
     * Test attribute "address1"
     */
    public function testPropertyAddress1()
    {

    }

    /**
     * Test attribute "address2"
     */
    public function testPropertyAddress2()
    {

    }

    /**
     * Test attribute "address3"
     */
    public function testPropertyAddress3()
    {

    }

    /**
     * Test attribute "address_city"
     */
    public function testPropertyAddressCity()
    {

    }

    /**
     * Test attribute "address_postcode"
     */
    public function testPropertyAddressPostcode()
    {

    }

    /**
     * Test attribute "address_country"
     */
    public function testPropertyAddressCountry()
    {

    }

    /**
     * Test attribute "website"
     */
    public function testPropertyWebsite()
    {

    }

    /**
     * Test attribute "tel"
     */
    public function testPropertyTel()
    {

    }

    /**
     * Test attribute "linkedin"
     */
    public function testPropertyLinkedin()
    {

    }

    /**
     * Test attribute "facebook"
     */
    public function testPropertyFacebook()
    {

    }

    /**
     * Test attribute "twitter"
     */
    public function testPropertyTwitter()
    {

    }

    /**
     * Test attribute "instagram"
     */
    public function testPropertyInstagram()
    {

    }

    /**
     * Test attribute "googleplus"
     */
    public function testPropertyGoogleplus()
    {

    }

    /**
     * Test attribute "logo"
     */
    public function testPropertyLogo()
    {

    }

    /**
     * Test attribute "snippet"
     */
    public function testPropertySnippet()
    {

    }

    /**
     * Test attribute "secret_key"
     */
    public function testPropertySecretKey()
    {

    }

    /**
     * Test attribute "access_token"
     */
    public function testPropertyAccessToken()
    {

    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {

    }

}
