<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Squiggle
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Squiggle API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Squiggle;

use \Squiggle\Configuration;
use \Squiggle\ApiClient;
use \Squiggle\ApiException;
use \Squiggle\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Squiggle
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addAddress
     *
     * .
     *
     */
    public function testAddAddress()
    {

    }

    /**
     * Test case for addFile
     *
     * .
     *
     */
    public function testAddFile()
    {

    }

    /**
     * Test case for addGlobalTemplate
     *
     * .
     *
     */
    public function testAddGlobalTemplate()
    {

    }

    /**
     * Test case for addSnippet
     *
     * .
     *
     */
    public function testAddSnippet()
    {

    }

    /**
     * Test case for addTemplate
     *
     * .
     *
     */
    public function testAddTemplate()
    {

    }

    /**
     * Test case for addUser
     *
     * .
     *
     */
    public function testAddUser()
    {

    }

    /**
     * Test case for deleteAddress
     *
     * .
     *
     */
    public function testDeleteAddress()
    {

    }

    /**
     * Test case for deleteFile
     *
     * .
     *
     */
    public function testDeleteFile()
    {

    }

    /**
     * Test case for deleteGlobalTemplate
     *
     * .
     *
     */
    public function testDeleteGlobalTemplate()
    {

    }

    /**
     * Test case for deleteSnippet
     *
     * .
     *
     */
    public function testDeleteSnippet()
    {

    }

    /**
     * Test case for deleteTemplate
     *
     * .
     *
     */
    public function testDeleteTemplate()
    {

    }

    /**
     * Test case for deleteUser
     *
     * .
     *
     */
    public function testDeleteUser()
    {

    }

    /**
     * Test case for editAddress
     *
     * .
     *
     */
    public function testEditAddress()
    {

    }

    /**
     * Test case for editFile
     *
     * .
     *
     */
    public function testEditFile()
    {

    }

    /**
     * Test case for editGlobalTemplate
     *
     * .
     *
     */
    public function testEditGlobalTemplate()
    {

    }

    /**
     * Test case for editSnippet
     *
     * .
     *
     */
    public function testEditSnippet()
    {

    }

    /**
     * Test case for editTemplate
     *
     * .
     *
     */
    public function testEditTemplate()
    {

    }

    /**
     * Test case for editUser
     *
     * .
     *
     */
    public function testEditUser()
    {

    }

    /**
     * Test case for findAddresses
     *
     * .
     *
     */
    public function testFindAddresses()
    {

    }

    /**
     * Test case for findFiles
     *
     * .
     *
     */
    public function testFindFiles()
    {

    }

    /**
     * Test case for findGlobalTemplates
     *
     * .
     *
     */
    public function testFindGlobalTemplates()
    {

    }

    /**
     * Test case for findSnippets
     *
     * .
     *
     */
    public function testFindSnippets()
    {

    }

    /**
     * Test case for findTemplates
     *
     * .
     *
     */
    public function testFindTemplates()
    {

    }

    /**
     * Test case for findUsers
     *
     * .
     *
     */
    public function testFindUsers()
    {

    }

    /**
     * Test case for getAddress
     *
     * .
     *
     */
    public function testGetAddress()
    {

    }

    /**
     * Test case for getAddressToken
     *
     * .
     *
     */
    public function testGetAddressToken()
    {

    }

    /**
     * Test case for getFile
     *
     * .
     *
     */
    public function testGetFile()
    {

    }

    /**
     * Test case for getGlobalTemplate
     *
     * .
     *
     */
    public function testGetGlobalTemplate()
    {

    }

    /**
     * Test case for getSnippet
     *
     * .
     *
     */
    public function testGetSnippet()
    {

    }

    /**
     * Test case for getTemplate
     *
     * .
     *
     */
    public function testGetTemplate()
    {

    }

    /**
     * Test case for getUser
     *
     * .
     *
     */
    public function testGetUser()
    {

    }

    /**
     * Test case for getUserToken
     *
     * .
     *
     */
    public function testGetUserToken()
    {

    }

}
